import { GoogleGenAI, Type } from "@google/genai";
import { AppState, GeneratedScript } from "../types";

export const generateImageFree = async (prompt: string, aspectRatio: '1:1' | '16:9' | '9:16' = '9:16', seed?: number): Promise<string> => {
  let width = 1024;
  let height = 1024;
  
  if (aspectRatio === '16:9') {
    width = 1024;
    height = 576;
  } else if (aspectRatio === '9:16') {
    width = 576;
    height = 1024;
  }

  // Pollinations.ai is a free URL-based image generation API (no key required)
  const encodedPrompt = encodeURIComponent(prompt);
  const finalSeed = seed ?? Math.floor(Math.random() * 1000000);
  const url = `https://image.pollinations.ai/prompt/${encodedPrompt}?width=${width}&height=${height}&seed=${finalSeed}&nologo=true`;
  
  try {
    const response = await fetch(url);
    if (!response.ok) {
      throw new Error(`Failed to fetch image: ${response.statusText}`);
    }
    const blob = await response.blob();
    return URL.createObjectURL(blob);
  } catch (error: any) {
    console.error("Free Image Generation Error:", error);
    throw new Error("Failed to generate free image. Please try again.");
  }
};

export const generateImage = async (prompt: string, aspectRatio: '1:1' | '16:9' | '9:16' = '9:16'): Promise<string> => {
  const apiKey = process.env.GEMINI_API_KEY;
  if (!apiKey) {
    throw new Error("GEMINI_API_KEY is not defined. Please set it in Settings.");
  }
  const ai = new GoogleGenAI({ apiKey });
  
  try {
    const response = await ai.models.generateContent({
      model: "gemini-3.1-flash-image",
      contents: {
        parts: [{ text: prompt }]
      },
      config: {
        imageConfig: {
          aspectRatio,
          numberOfImages: 1
        }
      }
    });

    for (const part of response.candidates?.[0]?.content?.parts || []) {
      if (part.inlineData && part.inlineData.data) {
        return `data:image/jpeg;base64,${part.inlineData.data}`;
      }
    }
    
    throw new Error("No image generated by Gemini");
  } catch (error: any) {
    console.error("Image Generation Error:", error);
    if (error.message?.includes("429") || error.message?.includes("Quota exceeded")) {
      throw new Error("API Quota Exceeded for image generation. Please try again tomorrow. Alternatively, use Gemini Imagen web UI directly as instructed.");
    }
    if (error.message?.includes("404")) {
      throw new Error("The image generation model is currently unavailable on this API key. Use the Gemini web UI for generating references.");
    }
    throw new Error(error.message || "Failed to generate image.");
  }
};

export const generateScriptPipeline = async (
  input: AppState,
): Promise<GeneratedScript> => {
  const apiKey = process.env.GEMINI_API_KEY;
  if (!apiKey) {
    throw new Error("GEMINI_API_KEY is not defined. Please set it in Settings.");
  }

  const ai = new GoogleGenAI({ apiKey });

  const systemInstruction = `Kamu adalah AI Director yang akan generate FULL PRODUCTION PACKAGE untuk video pendek Bahasa Indonesia (YT Shorts + FB Reels).

TUGASMU:
Generate JSON lengkap yang berisi SEMUA aset siap-eksekusi untuk pipeline berdasarkan input user.

ATURAN KETAT:
1. Output WAJIB JSON yang sesuai dengan schema rincian, tanpa ada teks di luarnya.
2. Semua "veo_prompt" (di array scenes) harus sudah LENGKAP dan siap copy-paste ke AI Video Generator. Harus include:
   - Tipe Shot (Close Up, Medium, Full Body)
   - Action/Pergerakan Karakter
   - "CHARACTER: [deskripsi singkat dari setting karakter master]" 
   - "LOCATION/TIME/LIGHTING: [dari setting master]"
   - "CAMERA: [deskripsi camera movement]"
   - "VISUAL STYLE: [dari user input]"
3. Pada \`stage_2_assets\`, hasilkan prompt untuk generator gambar berupa:
   - \`character_turnaround_prompt\`: Prompt untuk Character Reference Sheet (posisi Front, Side, dan Back/3-quarter).
   - \`setting_prompts\`: Daftar prompt untuk membuat visual latar/tempat kejadian utama cerita TANPA KARAKTER DI DALAMNYA.
4. Voiceover di tts_prompt harus diformat dengan tanda baca natural (titik, koma), HURUF KAPITAL untuk penekanan.
5. Durasi per scene maksimal 8 detik. Total seluruh scene (durasi_detik) harus SETARA dengan target durasi.
6. Target durasi: ${input.durasi} detik.
7. Hook 3 detik pertama (awal voiceover scene 1) HARUS bikin scroll-stop.`;

  const prompt = `
INPUT USER:
- Niche: ${input.niche}
- Ide: ${input.ide}
- Style visual: ${input.style}
- Durasi target: ${input.durasi} detik
- Deskripsi karakter: ${input.karakter}
- Tone/Voice Profile: ${input.tone}
`;

  try {
    const generationPromise = ai.models.generateContent({
      model: "gemini-2.5-flash",
      contents: prompt,
      config: {
        systemInstruction,
        responseMimeType: "application/json",
        responseSchema: {
          type: Type.OBJECT,
          properties: {
            metadata: {
              type: Type.OBJECT,
              properties: {
                judul_internal: { type: Type.STRING },
                estimasi_durasi: { type: Type.NUMBER },
                style_visual: { type: Type.STRING },
              },
              required: ["judul_internal", "estimasi_durasi", "style_visual"],
            },
            stage_1_script: {
              type: Type.OBJECT,
              properties: {
                hook_text: { type: Type.STRING },
                karakter_master: {
                  type: Type.OBJECT,
                  properties: {
                    nama: { type: Type.STRING },
                    deskripsi_fisik: { type: Type.STRING, description: "Detail fisik: wajar, rambut, pakaian" },
                    deskripsi_singkat: { type: Type.STRING, description: "Ringkasan deskripsi (max 25 kata) untuk diinject di tiap prompt" },
                    ekspresi_dominan: { type: Type.STRING },
                  },
                  required: ["nama", "deskripsi_fisik", "deskripsi_singkat", "ekspresi_dominan"],
                },
                setting_master: {
                  type: Type.OBJECT,
                  properties: {
                    lokasi: { type: Type.STRING },
                    waktu: { type: Type.STRING },
                    mood_lighting: { type: Type.STRING },
                  },
                  required: ["lokasi", "waktu", "mood_lighting"],
                },
                scenes: {
                  type: Type.ARRAY,
                  items: {
                    type: Type.OBJECT,
                    properties: {
                      scene_number: { type: Type.NUMBER },
                      durasi_detik: { type: Type.NUMBER },
                      voiceover_text: { type: Type.STRING, description: "Teks murni tanpa format khusus" },
                      veo_prompt: { type: Type.STRING, description: "Full prompt bahasa Inggris untuk Veo 3 Video Gen" },
                      tts_prompt: { type: Type.STRING, description: "Teks voiceover dgn HURUF KAPITAL dan titik-koma natural" },
                      visual_description: { type: Type.STRING },
                      camera_movement: { type: Type.STRING },
                      emotion_in_scene: { type: Type.STRING },
                    },
                    required: ["scene_number", "durasi_detik", "voiceover_text", "veo_prompt", "tts_prompt"],
                  },
                },
              },
              required: ["hook_text", "karakter_master", "setting_master", "scenes"],
            },
            stage_2_assets: {
              type: Type.OBJECT,
              description: "Prompts for generating reference images to maintain consistency.",
              properties: {
                character_turnaround_prompt: {
                  type: Type.STRING,
                  description: "Prompt bahasa Inggris untuk generator gambar membuat character reference sheet (multiple angles: front, side, back) di neutral background.",
                },
                setting_prompts: {
                  type: Type.ARRAY,
                  items: { type: Type.STRING },
                  description: "Daftar prompt bahasa Inggris untuk membuat establishing shots dari setting utama yang ada di cerita.",
                },
              },
              required: ["character_turnaround_prompt", "setting_prompts"],
            },
            stage_4_metadata: {
              type: Type.OBJECT,
              properties: {
                youtube_shorts: {
                  type: Type.OBJECT,
                  properties: {
                    judul: { type: Type.STRING, description: "Max 60 karakter" },
                    deskripsi: { type: Type.STRING },
                    hashtag: { type: Type.ARRAY, items: { type: Type.STRING } },
                    tags_seo: { type: Type.ARRAY, items: { type: Type.STRING } },
                  },
                  required: ["judul", "deskripsi", "hashtag"],
                },
                facebook_reels: {
                  type: Type.OBJECT,
                  properties: {
                    caption: { type: Type.STRING },
                    hashtag: { type: Type.ARRAY, items: { type: Type.STRING } },
                  },
                  required: ["caption", "hashtag"],
                },
                text_overlay: {
                  type: Type.OBJECT,
                  properties: {
                    hook_3_detik: { type: Type.STRING },
                    cta_akhir: { type: Type.STRING },
                  },
                  required: ["hook_3_detik", "cta_akhir"],
                },
                thumbnail_text_idea: { type: Type.STRING },
              },
              required: ["youtube_shorts", "facebook_reels", "text_overlay", "thumbnail_text_idea"],
            },
          },
          required: ["metadata", "stage_1_script", "stage_2_assets", "stage_4_metadata"],
        },
      },
    });

    const timeoutPromise = new Promise<never>((_, reject) => {
      setTimeout(() => reject(new Error("Generation timed out. The request took longer than 60 seconds. Please try again or simplify your request.")), 60000);
    });

    const response = await Promise.race([generationPromise, timeoutPromise]);

    const outputText = response.text;
    if (!outputText) {
      throw new Error("No response output from Gemini");
    }

    const payload = JSON.parse(outputText) as GeneratedScript;
    return payload;
  } catch (error) {
    if (error instanceof Error && error.message.includes("API_KEY")) {
      throw error;
    }
    console.error("Gemini Error:", error);
    throw new Error("Failed to generate script: " + (error as Error).message);
  }
};
